spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/prpp
spring.datasource.username=root
spring.datasource.password=Brigadeiro1612!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
