spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/prpp?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=laisjoao
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
